// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignees.sql

package store

import (
	"context"
)

const addNodeAssignee = `-- name: AddNodeAssignee :exec
INSERT INTO node_assignees (node_id, actor, created_at) VALUES (?, ?, ?)
ON CONFLICT (node_id, actor) DO NOTHING
`

type AddNodeAssigneeParams struct {
	NodeID    string
	Actor     string
	CreatedAt string
}

func (q *Queries) AddNodeAssignee(ctx context.Context, arg AddNodeAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, addNodeAssignee, arg.NodeID, arg.Actor, arg.CreatedAt)
	return err
}

const deleteNodeAssigneesForNode = `-- name: DeleteNodeAssigneesForNode :exec
DELETE FROM node_assignees WHERE node_id = ?
`

func (q *Queries) DeleteNodeAssigneesForNode(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAssigneesForNode, nodeID)
	return err
}

const listNodeAssignees = `-- name: ListNodeAssignees :many
SELECT actor FROM node_assignees WHERE node_id = ? ORDER BY created_at
`

func (q *Queries) ListNodeAssignees(ctx context.Context, nodeID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNodeAssignees, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actor string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNodeAssignee = `-- name: RemoveNodeAssignee :exec
DELETE FROM node_assignees WHERE node_id = ? AND actor = ?
`

type RemoveNodeAssigneeParams struct {
	NodeID string
	Actor  string
}

func (q *Queries) RemoveNodeAssignee(ctx context.Context, arg RemoveNodeAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, removeNodeAssignee, arg.NodeID, arg.Actor)
	return err
}
