// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package store

import (
	"context"
)

const addNodeLabel = `-- name: AddNodeLabel :exec
INSERT INTO node_labels (node_id, label_id) VALUES (?, ?)
ON CONFLICT (node_id, label_id) DO NOTHING
`

type AddNodeLabelParams struct {
	NodeID  string
	LabelID string
}

func (q *Queries) AddNodeLabel(ctx context.Context, arg AddNodeLabelParams) error {
	_, err := q.db.ExecContext(ctx, addNodeLabel, arg.NodeID, arg.LabelID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (id, workspace_id, name, color, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, workspace_id, name, color, created_at
`

type CreateLabelParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Color       string
	CreatedAt   string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
		arg.CreatedAt,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, name, color, created_at FROM labels WHERE id = ?
`

func (q *Queries) GetLabel(ctx context.Context, id string) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listLabelsByWorkspace = `-- name: ListLabelsByWorkspace :many
SELECT id, workspace_id, name, color, created_at FROM labels WHERE workspace_id = ? ORDER BY name
`

func (q *Queries) ListLabelsByWorkspace(ctx context.Context, workspaceID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeLabels = `-- name: ListNodeLabels :many
SELECT l.id, l.workspace_id, l.name, l.color, l.created_at FROM labels l
JOIN node_labels nl ON nl.label_id = l.id
WHERE nl.node_id = ?
ORDER BY l.name
`

func (q *Queries) ListNodeLabels(ctx context.Context, nodeID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listNodeLabels, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNodeLabel = `-- name: RemoveNodeLabel :exec
DELETE FROM node_labels WHERE node_id = ? AND label_id = ?
`

type RemoveNodeLabelParams struct {
	NodeID  string
	LabelID string
}

func (q *Queries) RemoveNodeLabel(ctx context.Context, arg RemoveNodeLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeNodeLabel, arg.NodeID, arg.LabelID)
	return err
}
