// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Activity struct {
	ID        string
	NodeID    string
	Actor     string
	Kind      string
	Data      string
	CreatedAt string
}

type Label struct {
	ID          string
	WorkspaceID string
	Name        string
	Color       string
	CreatedAt   string
}

type Node struct {
	ID          string
	WorkspaceID string
	Seq         int64
	Key         string
	ParentID    sql.NullString
	Title       string
	Description string
	StatusID    sql.NullString
	Priority    int64
	CreatedAt   string
	UpdatedAt   string
	Origin      string
	ProposedBy  string
	SourceWs    string
}

type NodeAssignee struct {
	NodeID    string
	Actor     string
	CreatedAt string
}

type NodeLabel struct {
	NodeID  string
	LabelID string
}

type Relation struct {
	ID        string
	FromNode  string
	ToNode    string
	Kind      string
	CreatedAt string
}

type Status struct {
	ID          string
	WorkspaceID string
	Category    string
	Name        string
	Color       string
	Position    int64
	CreatedAt   string
}

type Workspace struct {
	ID          string
	Key         string
	Name        string
	Description string
	NodeSeq     int64
	CreatedAt   string
	UpdatedAt   string
}
