// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"database/sql"
)

const countChildren = `-- name: CountChildren :one
SELECT COUNT(*) FROM nodes WHERE parent_id = ?
`

func (q *Queries) CountChildren(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, workspace_id, seq, key, parent_id, title, description, status_id, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at
`

type CreateNodeParams struct {
	ID          string
	WorkspaceID string
	Seq         int64
	Key         string
	ParentID    sql.NullString
	Title       string
	Description string
	StatusID    sql.NullString
	Priority    int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.ID,
		arg.WorkspaceID,
		arg.Seq,
		arg.Key,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at FROM nodes WHERE id = ?
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByKey = `-- name: GetNodeByKey :one
SELECT id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at FROM nodes WHERE key = ?
`

func (q *Queries) GetNodeByKey(ctx context.Context, key string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByKey, key)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildStatusCategories = `-- name: ListChildStatusCategories :many
SELECT s.category AS category, COUNT(*) AS cnt
FROM nodes n
LEFT JOIN statuses s ON s.id = n.status_id
WHERE n.parent_id = ?
GROUP BY s.category
`

type ListChildStatusCategoriesRow struct {
	Category sql.NullString
	Cnt      int64
}

// Rollup input: status categories of a node's DIRECT children (the derived
// aggregate itself is computed by the service layer).
func (q *Queries) ListChildStatusCategories(ctx context.Context, parentID sql.NullString) ([]ListChildStatusCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildStatusCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildStatusCategoriesRow
	for rows.Next() {
		var i ListChildStatusCategoriesRow
		if err := rows.Scan(&i.Category, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at FROM nodes WHERE parent_id = ? ORDER BY priority, seq
`

func (q *Queries) ListChildren(ctx context.Context, parentID sql.NullString) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByWorkspace = `-- name: ListNodesByWorkspace :many
SELECT id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at FROM nodes WHERE workspace_id = ? ORDER BY priority, seq
`

// Flat list of a workspace's nodes. Ordered by priority (lower = higher priority,
// P0 first), then seq for stable tie-break. parent/status filters are applied
// in-memory by the service layer (v0 scale; keeps SQL portable, no dynamic SQL).
func (q *Queries) ListNodesByWorkspace(ctx context.Context, workspaceID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootNodes = `-- name: ListRootNodes :many
SELECT id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at FROM nodes WHERE workspace_id = ? AND parent_id IS NULL ORDER BY priority, seq
`

func (q *Queries) ListRootNodes(ctx context.Context, workspaceID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listRootNodes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET title = ?, description = ?, status_id = ?, priority = ?, parent_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, seq, "key", parent_id, title, description, status_id, priority, created_at, updated_at
`

type UpdateNodeParams struct {
	Title       string
	Description string
	StatusID    sql.NullString
	Priority    int64
	ParentID    sql.NullString
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.ParentID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
