// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relations.sql

package store

import (
	"context"
)

const createRelation = `-- name: CreateRelation :one
INSERT INTO relations (id, from_node, to_node, kind, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, from_node, to_node, kind, created_at
`

type CreateRelationParams struct {
	ID        string
	FromNode  string
	ToNode    string
	Kind      string
	CreatedAt string
}

func (q *Queries) CreateRelation(ctx context.Context, arg CreateRelationParams) (Relation, error) {
	row := q.db.QueryRowContext(ctx, createRelation,
		arg.ID,
		arg.FromNode,
		arg.ToNode,
		arg.Kind,
		arg.CreatedAt,
	)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.FromNode,
		&i.ToNode,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM relations WHERE id = ?
`

func (q *Queries) DeleteRelation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRelation, id)
	return err
}

const getRelation = `-- name: GetRelation :one
SELECT id, from_node, to_node, kind, created_at FROM relations WHERE id = ?
`

func (q *Queries) GetRelation(ctx context.Context, id string) (Relation, error) {
	row := q.db.QueryRowContext(ctx, getRelation, id)
	var i Relation
	err := row.Scan(
		&i.ID,
		&i.FromNode,
		&i.ToNode,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listRelationsForNode = `-- name: ListRelationsForNode :many
SELECT id, from_node, to_node, kind, created_at FROM relations
WHERE from_node = ? OR to_node = ?
ORDER BY created_at
`

type ListRelationsForNodeParams struct {
	FromNode string
	ToNode   string
}

// All links where the node is source OR target (typed links visible both ways).
func (q *Queries) ListRelationsForNode(ctx context.Context, arg ListRelationsForNodeParams) ([]Relation, error) {
	rows, err := q.db.QueryContext(ctx, listRelationsForNode, arg.FromNode, arg.ToNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relation
	for rows.Next() {
		var i Relation
		if err := rows.Scan(
			&i.ID,
			&i.FromNode,
			&i.ToNode,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
