// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package store

import (
	"context"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO statuses (id, workspace_id, category, name, color, position, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, category, name, color, position, created_at
`

type CreateStatusParams struct {
	ID          string
	WorkspaceID string
	Category    string
	Name        string
	Color       string
	Position    int64
	CreatedAt   string
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRowContext(ctx, createStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.Category,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.CreatedAt,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Category,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getStatus = `-- name: GetStatus :one
SELECT id, workspace_id, category, name, color, position, created_at FROM statuses WHERE id = ?
`

func (q *Queries) GetStatus(ctx context.Context, id string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Category,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listStatusesByWorkspace = `-- name: ListStatusesByWorkspace :many
SELECT id, workspace_id, category, name, color, position, created_at FROM statuses WHERE workspace_id = ? ORDER BY position, created_at
`

func (q *Queries) ListStatusesByWorkspace(ctx context.Context, workspaceID string) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, listStatusesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Category,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
