// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"
)

const bumpWorkspaceNodeSeq = `-- name: BumpWorkspaceNodeSeq :one
UPDATE workspaces
SET node_seq = node_seq + 1, updated_at = ?
WHERE id = ?
RETURNING node_seq
`

type BumpWorkspaceNodeSeqParams struct {
	UpdatedAt string
	ID        string
}

// Transactional per-workspace node.seq counter (monotonic, never decreases).
// RETURNING is supported by both modernc SQLite and pgx/PG. Called inside a Tx
// together with the nodes INSERT so key allocation is atomic.
func (q *Queries) BumpWorkspaceNodeSeq(ctx context.Context, arg BumpWorkspaceNodeSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpWorkspaceNodeSeq, arg.UpdatedAt, arg.ID)
	var node_seq int64
	err := row.Scan(&node_seq)
	return node_seq, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, key, name, description, node_seq, created_at, updated_at)
VALUES (?, ?, ?, ?, 0, ?, ?)
RETURNING id, "key", name, description, node_seq, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID          string
	Key         string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NodeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, "key", name, description, node_seq, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NodeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByKey = `-- name: GetWorkspaceByKey :one
SELECT id, "key", name, description, node_seq, created_at, updated_at FROM workspaces WHERE key = ?
`

func (q *Queries) GetWorkspaceByKey(ctx context.Context, key string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByKey, key)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NodeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, "key", name, description, node_seq, created_at, updated_at FROM workspaces ORDER BY created_at, key
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.NodeSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = ?, description = ?, updated_at = ?
WHERE id = ?
RETURNING id, "key", name, description, node_seq, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	Name        string
	Description string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NodeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
